// src/Components/Scoreboard/Scoreboard.tsx
import React from "react";
import { Row, Col } from "antd";
import { GameStatut, LiveSettings, Quarter, TeamPossession } from "../../Models";
import './Scoreboard.css';
import { IpcService } from "../../utils/IpcService";
import { GameClock } from "..";

const ipc = new IpcService();

type ScoreboardProps = {
};
type ScoreboardState = {
  GameStatut?: GameStatut;
  LiveSettings?: LiveSettings;
  ipcrenderer?: Electron.IpcRenderer;
};
class Scoreboard extends React.Component<ScoreboardProps, ScoreboardState> {

  constructor(props: Readonly<ScoreboardProps>) {
    super(props);
    this.state = {      
    };
  }

  componentDidMount = async () => {
    try {
      let ipcrenderer = await ipc.receiveUpdate('scoreboard-update', { responseChannel: 'scoreboard-update' });
      await this.setState({ ipcrenderer })
      this.state.ipcrenderer?.on('scoreboard-update', this.onData);
    } catch (error) {
    }
  }

  componentWillUnmount = async () => {
    try {
      if (this.state.ipcrenderer) {
        this.state.ipcrenderer.removeListener('scoreboard-update', this.onData);
        await this.setState({ ipcrenderer: undefined });
      }
    } catch (error) {
      console.log(error);
    }
  }

  onData = async (event: any, response: any) => {
    await this.setState({
      GameStatut: response.GameStatut,
      LiveSettings: response.LiveSettings,
    })
  };
  
  render() {
    const homeTeam = this.state.GameStatut?.HomeTeam;
    const awayTeam = this.state.GameStatut?.AwayTeam;

    return (
      <div style={{ width: '100%', height: '100vh', backgroundColor: 'green', paddingTop: 25 }}>
        <Row gutter={[0, 0]}>
          <Col span={24}>
            <div className="scoreAndTime" style={{ display: 'flex', flexDirection: 'row', justifyContent: "center" }}>

              <div className="teamblock-scoreboard" style={{ width: '360px', background: homeTeam?.color }} >
                <img className='img-thumbnail teamlogo-scoreboard noselect' alt='home team logo' src={ homeTeam?.logo } />
                <div className="teamname-scoreboard noselect" style={{ fontWeight: 700 }}>
                  { homeTeam?.name }
                </div>
                <div className="teamscore-scoreboard noselect" style={{ fontWeight: 700 }}>
                  { homeTeam?.score.toLocaleString('fr-FR', { minimumIntegerDigits:2, useGrouping: false }) }
                </div>
                <div className="teamtimeoutblock-scoreboard noselect">
                  { homeTeam?.timeout && homeTeam?.timeout >= 1 && <div className="teamtimeout-scoreboard bg-warning"></div> }
                  { homeTeam?.timeout && homeTeam?.timeout >= 2 && <div className="teamtimeout-scoreboard bg-warning"></div> }
                  { homeTeam?.timeout && homeTeam?.timeout >= 3 && <div className="teamtimeout-scoreboard bg-warning"></div> }
                </div>
                { this.state.GameStatut?.Options.possession === TeamPossession.HOME && <div className="teampossession-scoreboard bg-warning noselect"></div> }
              </div>

              <div className="teamblock-scoreboard" style={{ marginLeft: '5px', width: '360px', background: awayTeam?.color }} >
                <img className='img-thumbnail teamlogo-scoreboard noselect' alt='home team logo' src={ awayTeam?.logo } />
                <div className="teamname-scoreboard noselect" style={{ fontWeight: 700 }}>
                  { awayTeam?.name }
                </div>
                <div className="teamscore-scoreboard noselect" style={{ fontWeight: 700 }}>
                  { awayTeam?.score.toLocaleString('fr-FR', { minimumIntegerDigits:2, useGrouping: false }) }
                </div>
                <div className="teamtimeoutblock-scoreboard noselect">
                  { awayTeam?.timeout && awayTeam?.timeout >= 1 && <div className="teamtimeout-scoreboard bg-warning"></div> }
                  { awayTeam?.timeout && awayTeam?.timeout >= 2 && <div className="teamtimeout-scoreboard bg-warning"></div> }
                  { awayTeam?.timeout && awayTeam?.timeout >= 3 && <div className="teamtimeout-scoreboard bg-warning"></div> }
                </div>
                { this.state.GameStatut?.Options.possession === TeamPossession.AWAY && <div className="teampossession-scoreboard bg-warning noselect"></div> }
              </div>

              <div className="teamblock-scoreboard" style={{ marginLeft: '5px', width: this.state.GameStatut?.Options.clock.active ? 180 : 145, background: '#333333', position: 'relative', overflow: "hidden" }}>
                <div className="quarter-scoreboard" style={{ textAlign: "center", fontWeight: 700, color: 'white'}}>
                  <p className='noselect' style={{ transform: 'skewX(25deg)', margin: 0 }}>
                    { this.state.GameStatut?.Options.clock.active && <GameClock clock={this.state.GameStatut?.Options.clock}></GameClock> }
                    <span className='noselect'>{ this.state.GameStatut?.Options.quarter === Quarter.OT ? 'OT' : 'Q' + this.state.GameStatut?.Options.quarter }</span>
                  </p>
                </div>
                <div className="quarter-scoreboard bg-warning noselect" style={{ 
                  textAlign: "center", 
                  fontWeight: 700, 
                  color: "black", 
                  position: "absolute", 
                  top: 0, 
                  right: this.state.GameStatut?.Options.flag ? 0 : this.state.GameStatut?.Options.clock.active ? 180 : 145, 
                  width: this.state.GameStatut?.Options.clock.active ? 180 : 145, 
                  transition: "all ease 0.8s" 
                }}>
                  <p className='noselect' style={{ transform: 'skewX(25deg)', margin: 0 }}>FLAG</p>
                </div>
              </div>

            </div>
          </Col>
        </Row>
      </div>
    );
  }
};

export { Scoreboard };

// src/app/pages/stream/game-control/scoreboard/scoreboard.component.ts
import {
  Component,
  OnInit,
  Input,
  ElementRef,
  ViewChild,
  AfterViewInit,
  OnChanges,
  SimpleChanges
} from '@angular/core';
import { Team } from 'src/app/shared/models/team.model';
import { ElectronService } from 'ngx-electron';
import { TeamPossession } from 'src/app/shared/enums/team-possession.enum';
import { GameOptions } from 'src/app/shared/models/game-options.model';

@Component({
  selector: 'ngx-scoreboard',
  templateUrl: './scoreboard.component.html',
  styleUrls: ['./scoreboard.component.scss']
})
export class ScoreboardComponent implements OnInit, AfterViewInit, OnChanges {

  @ViewChild('scoreboard', null) el: ElementRef;

  @Input() homeTeam: Team = null;
  @Input() awayTeam: Team = null;
  @Input() gameOptions: GameOptions = null;

  constructor(private electronService: ElectronService) { }

  ngOnInit(): void { }

  ngAfterViewInit(): void {
    this.updateScoreBoard(this.el.nativeElement.innerHTML);
  }

  ngOnChanges(changes: SimpleChanges): void {
    setTimeout(() => {
      this.updateScoreBoard(this.el.nativeElement.innerHTML);
    }, 1);
  }

  updateScoreBoard(content: string) {
    const html = '<html> \
      <head> \
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"> \
        <style type="text/css"> \
          body {\
            background-color: rgba(0, 0, 0, 0); \
            margin: 0px auto; \
            overflow: hidden; \
            width: 1920px; \
            height: 76px; \
          } \
          .teamlogo-scoreboard { \
            height: 50px; \
            transform: skewX(25deg); \
            position: absolute; \
            left: 10px; \
            background: none; \
            border: none; \
          } \
          .teamname-scoreboard { \
            transform: skewX(25deg); \
            position: absolute; \
            left: 70px; \
            font-size: 30px; \
            line-height: 50px; \
            max-width: 225px; \
            white-space: nowrap; \
            overflow: hidden; \
            text-overflow: ellipsis; \
          } \
          .teamscore-scoreboard { \
            transform: skewX(25deg); \
            position: absolute; \
            right: 15px; \
            font-size: 30px; \
            line-height: 50px; \
          } \
          .teamblock-scoreboard { \
            height: 50px; \
            transform: skewX(-25deg); \
          } \
          .teampossession-scoreboard { \
            height: 3px; \
            position: absolute; \
            bottom: -3px; \
            width: 100%; \
          } \
          .teamtimeoutblock-scoreboard { \
            display: flex; \
            position: absolute; \
            bottom: -13px; \
          } \
            .teamtimeout-scoreboard { \
              width: 25px; \
              height: 7px; \
              margin-right: 3px; \
            } \
            .teamtimeout-scoreboard:last-child { \
              margin-right: 0; \
            } \
          .quarter-scoreboard { \
            transform: skewX(25deg); \
            font-size: 30px; \
            line-height: 50px; \
          } \
        </style> \
        <meta http-equiv="refresh" content="1"> \
      </head> \
      <body> \
        <div style="position: absolute; right: 55px; top: 40px;"> \
          ' + content + ' \
        </div> \
      </body> \
    </html>';
    // tslint:disable-next-line: no-unused-expression
    new Promise<any>((resolve, reject) => {
      if (this.electronService.isElectronApp) {
        this.electronService.ipcRenderer.once('updateScoreboardHTMLResponse', (event, arg) => {
          resolve(arg);
        });
        this.electronService.ipcRenderer.send('updateScoreboardHTML', html);
      } else {
        resolve(null);
      }
    });
  }

  checkPossessionHome(possession: TeamPossession) {
    return possession === TeamPossession.HOME;
  }

}

<div #scoreboard class="p-5 mx-auto jumbotron">
  <!-- <div class="downs">

  </div> -->
  <div class="scoreAndTime d-flex flex-row">

    <div class="teamblock-scoreboard" [ngStyle]="{ 'width': '360px', 'background': homeTeam.color }" [ngxAdapteTextColorToBg]="homeTeam.color">
      <img class="img-thumbnail teamlogo-scoreboard" *ngIf="homeTeam.logo.startsWith('http')" src="{{ homeTeam.logo }}" />
      <img class="img-thumbnail teamlogo-scoreboard" *ngIf="!homeTeam.logo.startsWith('http')" [src]="homeTeam.logo | safe: 'resourceUrl'" />
      <div class="teamname-scoreboard font-weight-bold">
        {{ homeTeam.name }}
      </div>
      <div class="teamscore-scoreboard font-weight-bold">
        {{ homeTeam.score | number: "2.0-0" }}
      </div>
      <div class="teamtimeoutblock-scoreboard">
        <div *ngIf="homeTeam.timeout >= 1" class="teamtimeout-scoreboard bg-warning"></div>
        <div *ngIf="homeTeam.timeout >= 2" class="teamtimeout-scoreboard bg-warning"></div>
        <div *ngIf="homeTeam.timeout >= 3" class="teamtimeout-scoreboard bg-warning"></div>
      </div>
      <div *ngIf="checkPossessionHome(gameOptions.possession)"  class="teampossession-scoreboard bg-warning"></div>
    </div>

    <div class="teamblock-scoreboard" [ngStyle]="{ 'margin-left': '5px', 'width': '360px', 'background': awayTeam.color }" [ngxAdapteTextColorToBg]="awayTeam.color">
      <img class="img-thumbnail teamlogo-scoreboard" *ngIf="awayTeam.logo.startsWith('http')" src="{{ awayTeam.logo }}" />
      <img class="img-thumbnail teamlogo-scoreboard" *ngIf="!awayTeam.logo.startsWith('http')" [src]="awayTeam.logo | safe: 'resourceUrl'" />
      <div class="teamname-scoreboard font-weight-bold">
        {{ awayTeam.name }}
      </div>
      <div class="teamscore-scoreboard font-weight-bold">
        {{ awayTeam.score | number: "2.0-0" }}
      </div>
      <div class="teamtimeoutblock-scoreboard">
        <div *ngIf="awayTeam.timeout >= 1" class="teamtimeout-scoreboard bg-warning"></div>
        <div *ngIf="awayTeam.timeout >= 2" class="teamtimeout-scoreboard bg-warning"></div>
        <div *ngIf="awayTeam.timeout >= 3" class="teamtimeout-scoreboard bg-warning"></div>
      </div>
      <div *ngIf="!checkPossessionHome(gameOptions.possession)" class="teampossession-scoreboard bg-warning"></div>
    </div>

    <div class="teamblock-scoreboard" *ngIf="!gameOptions.flag" [ngStyle]="{ 'margin-left': '5px', 'width': '145px', 'background': '#333333' }" [ngxAdapteTextColorToBg]="'#333333'">
      <div class="quarter-scoreboard text-center font-weight-bold">
        Q{{ gameOptions.quarter }}
      </div>
    </div>
    <div class="teamblock-scoreboard bg-warning" *ngIf="gameOptions.flag" [ngStyle]="{ 'margin-left': '5px', 'width': '145px' }" [ngxAdapteTextColorToBg]="'#ffaa00'">
      <div class="quarter-scoreboard text-center font-weight-bold">
        FLAG
      </div>
    </div>

  </div>
  <!-- <div class="ballOn">

  </div> -->
</div>
